version: "3"

services:
  jupyter:
    entrypoint: ""
    command: jupyter notebook --ip=0.0.0.0 --allow-root --no-browser --port 8080 --NotebookApp.token=token --NotebookApp.notebook_dir=/working
    image: gcr.io/kaggle-gpu-images/python:latest
    runtime: nvidia
    environment:
      LD_LIBRARY_PATH: "/usr/local/cuda/lib64::/opt/conda/lib"
    user: root
    ports:
      - "8080:8080"
    volumes:
      - ./working:/working
      - /data:/input
      - /usr/local/cuda:/usr/local/cuda
    working_dir: /

